### ISSUE TITLE
Strict ratelimiting via global consensus

### ISSUE THREAD

**Issue by chronark** [chronark/unkey#14]

**Comment by CITGuru** [comment]
@chronark are you working on this, if no, can you provide more context?

**Comment by chronark** [comment]
https://docs.unkey.dev/features/ratelimiting#global-consensus-rate-limiting

we need a way to strictly ensure ratelimits regardless of machine or location handling the request

I'm currently rewriting the API in go, and we can then implement this based on redis most likely
