### ISSUE TITLE
App redirected too many times

### ISSUE THREAD

**Issue by shawshankkumar** [chronark/unkey#45]
When I login using gmail, this page keeps redirecting: https://unkey.dev/app
![Screenshot (2718)](https://github.com/chronark/unkey/assets/74819565/13befc06-1b20-45ad-ad17-e97f4541c26a)

**Comment by chronark** [comment]
Cc @perkinsjr

**Comment by perkinsjr** [comment]
hay that mystery bug! I saw earlier is back. 

Looking

**Comment by perkinsjr** [comment]
hey @shawshankkumar can you go to:

https://unkey.dev/auth/sign-up and attempt to sign up. 

If you get redirect looping again can you go to https://unkey.dev/onboarding which will allow you to create your workspace and stop all the issues.

I am still digging into why this happens but this should get you going.

**Comment by perkinsjr** [comment]
This is now fixed and should redirect you correctly

**Comment by shawshankkumar** [comment]
@perkinsjr it is, that was fast 🐎
