### ISSUE TITLE
Stale data when creating a API and coming back to the APIs page

### ISSUE THREAD

**Issue by remorses** [chronark/unkey#46]
This is a known problem with Next.js app router: https://github.com/vercel/next.js/issues/42991

I open this issue because i am curious to see how you solve it 👀

One way would be to call `revalidatePath` but that was bugged too last time i tried it

**Comment by chronark** [comment]
ouch, yeah let me see what I can do :)

**Comment by duongductrong** [comment]
I waited for the owner to fix this issue, but after more than 2 version releases it's still not resolved, I wish I can understand the codebase of next.js to create a third party to resolve this issue.

**Comment by perkinsjr** [comment]
This should be fixed with the latest update
