### ISSUE TITLE
Make the root API key hidden by default

### ISSUE THREAD

**Issue by Jonxslays** [chronark/unkey#47]
For security, it would be best if the root API key were hidden like in a password field by default with the copy button and potentially a show/hide button as well.

I would be happy to contribute this.

**Comment by chronark** [comment]
Absolutely, good point, actually all keys should be hidden

Yes please!

**Comment by Jonxslays** [comment]
When I first created this issue I thought the api ID was the key used to manage the api. Got confused because they all look pretty much the same. I see now the prefix indicates what each one is though.

Based on that I think the current implementation is ok, unless you'd like to hide the first 3 digits of the actual key altogether - so something like `prefix_***`?

**Comment by chronark** [comment]
Oh I thought you were referring to when you create a new key in the dialog box

**Comment by Jonxslays** [comment]
you're right, it does actually apply to that lol.
