### ISSUE TITLE
Tentative Elixir SDK

### ISSUE THREAD

**Issue by glamboyosa** [chronark/unkey#48]
Hi I saw a tweet from @chronark https://twitter.com/chronark_/status/1671626313558261763?s=46&t=mo1Vl4m1gGQKGdXzA6KgkQ about potentially building an SDK in TS and the community building one in Elixir and I just wanted to pop in and offer to build one in Elixir for the community. I'm an engineer with 3 years experience with JS / TS and Elixir and I think the community would benefit from having a package as it's usually forgotten. 

https://github.com/glamboyosa/ex-cleanse is an example of a small package I wrote in TS for Elixir. 

Cheers.

**Comment by chronark** [comment]
amazing, let's go

we're already talking about a python sdk on discord too, let's talk there if you don't mind
or we can continue here, either way works
https://discord.gg/sfxtt7an

**Comment by CITGuru** [comment]
@chronark I can pick up the Python package if no one is working on that

**Comment by perkinsjr** [comment]
@CITGuru we already have a python SDK in the works (https://jonxslays.github.io/unkey.py/v0.2.0/)

**Comment by CITGuru** [comment]
Okay then. Cool
