### ISSUE TITLE
[ui] 2 Minor UI fixes.

### ISSUE THREAD

**Issue by thesatyam05** [chronark/unkey#54]
Issue: 2 Minor UI fixes

😄 **I am willing to fix this issue,** Can I? and create the pull request right away? @chronark  @perkinsjr 

### 1. Like all other clickable items on the website has cursor of pointer. but this is not the case with WorkspaceSwitcher's buttons.
- ![image](https://github.com/chronark/unkey/assets/85938434/98aa0cb0-ef38-4734-bccc-62636782cc0b)

### 2. The signout button container is not taking up the whole space.
- ![image](https://github.com/chronark/unkey/assets/85938434/f6afe70f-78c7-416e-bc5e-3000d52cd752)

**Comment by perkinsjr** [comment]
go for it 👍

**Comment by thesatyam05** [comment]
can you help me with setting up the local dev server?

**Comment by perkinsjr** [comment]
I ended up taking care of this, with a few other UI fixes. Due to us not having our contribution guide ready to go. 

Appreciate you open issues and offering, our guide should be out this week
