### ISSUE TITLE
[ui] Minor UI Fix required ( Only for Firefox may be )

### ISSUE THREAD

**Issue by thesatyam05** [chronark/unkey#60]
#### Note: this issue is only seen on Firefox web browser as of now.

- Firefox
![image](https://github.com/chronark/unkey/assets/85938434/fe9203ce-b619-4e51-97f6-7e21c827858b)

- Google chrome
![image](https://github.com/chronark/unkey/assets/85938434/89edcdc7-ff02-466f-a410-f17ac71f905e)

**Comment by chronark** [comment]
oh wow, what's happening here?
I have no idea why that's happening

**Comment by chronark** [comment]
Oh wow yeah, looks like this is also broken in the upstream repo
thanks for sharing
