### ISSUE TITLE
Broken Link in README file

### ISSUE THREAD

**Issue by tutizaraz** [chronark/unkey#71]
I've found a documentation bug in the README file. When clicking on the [CONTRIBUTING](https://github.com/chronark/unkey/blob/main/.github/CONTRIBUTING) link, it redirects to a 404 page not found error.

It seems like the CONTRIBUTING.md file may have been moved, renamed, or deleted which is causing this broken link. 

Thank you for your attention to this matter.

**Comment by chronark** [comment]
Thanks, fixed it locally, will push soon

**Comment by tutizaraz** [comment]
Cool, I might join the project's development soon. It would be great if you could create as many tasks as possible, for both frontend and backend.

**Comment by chronark** [comment]
awesome
yeah I'm notoriously bad at it but I'll make an effort to add more issues

**Comment by WilfredAlmeida** [comment]
I've opened a PR for the same, missed this issue & it was a quick fix from the browser :)

https://github.com/chronark/unkey/pull/77
