### ISSUE TITLE
Multiple created APIs not visible on dashboard

### ISSUE THREAD

**Issue by WilfredAlmeida** [chronark/unkey#79]
Created APIs are not listed in the workspace until the page is refreshed. Please watch the following video as its hard to explain in text

https://github.com/chronark/unkey/assets/60785452/00dde100-f068-4a7e-baa6-8d058fe6a0c2

**Comment by chronark** [comment]
Ah, should be an easy fix. I think we're just not refreshing the router, thanks for the report

**Comment by perkinsjr** [comment]
Relates to #46

**Comment by perkinsjr** [comment]
This was fixed
